"""엄슨(UMSN) 어휘 사전.

파이썬 이름/기호 ↔ 엄슨 단어의 1:1(단사) 대응표를 정의한다.
모든 엄슨 단어는 한글(+숫자, ``_``)로만 이루어지며, ``엄!``/``엄?`` 처럼
느낌표·물음표로 끝나는 단어와 ``..`` 로 시작하는 기호어가 따로 있다.
"""

from collections import OrderedDict

# ---------------------------------------------------------------------------
# 1. 예약어 (keyword + soft keyword)
# ---------------------------------------------------------------------------
KEYWORDS = OrderedDict([
    ("def", "엄슨하다"),
    ("if", "어엄슨"),
    ("elif", "슨엄어엄슨"),
    ("else", "슨엄"),
    ("return", "엄슨한"),
    ("yield", "슨엄한"),
    ("for", "엄슨마다"),
    ("while", "엄슨동안"),
    ("in", "엄속"),
    ("not", "안엄슨"),
    ("and", "엄그리고"),
    ("or", "엄또는"),
    ("is", "엄이다"),
    ("True", "엄슨참"),
    ("False", "슨엄거짓"),
    ("None", "엄없슨"),
    ("class", "엄슨틀"),
    ("import", "엄슨가져와"),
    ("from", "엄에서"),
    ("as", "엄으로"),
    ("try", "엄시도"),
    ("except", "엄슨예외"),
    ("finally", "엄마침내"),
    ("raise", "엄슨던져"),
    ("with", "엄슨함께"),
    ("lambda", "어엄"),
    ("pass", "엄"),
    ("break", "엄슨멈춰"),
    ("continue", "엄슨계속"),
    ("global", "엄전역"),
    ("nonlocal", "엄비지역"),
    ("del", "엄슨지워"),
    ("assert", "엄슨단언"),
    ("async", "엄비동기"),
    ("await", "엄기다려"),
    ("match", "엄슨맞춰"),
    ("case", "엄경우"),
])

# ---------------------------------------------------------------------------
# 2. 내장 함수 / 내장 상수 / 예외
# ---------------------------------------------------------------------------
BUILTINS = OrderedDict([
    ("print", "엄!"),
    ("input", "엄?"),
    ("help", "엄도와?"),
    ("abs", "엄절댓값"),
    ("all", "엄모두"),
    ("any", "엄하나라도"),
    ("ascii", "엄아스키"),
    ("bin", "엄이진"),
    ("bool", "엄불"),
    ("breakpoint", "엄중단점"),
    ("bytearray", "엄바이트배열"),
    ("bytes", "엄바이트"),
    ("callable", "엄부를수있나"),
    ("chr", "엄글자"),
    ("classmethod", "엄틀메소드"),
    ("compile", "엄컴파일"),
    ("complex", "엄복소수"),
    ("delattr", "엄속성지워"),
    ("dict", "엄사전"),
    ("dir", "엄목록보기"),
    ("divmod", "엄몫나머지"),
    ("enumerate", "엄번호매겨"),
    ("eval", "엄계산해"),
    ("exec", "엄실행해"),
    ("exit", "엄나가"),
    ("filter", "엄걸러"),
    ("float", "엄실수"),
    ("format", "엄서식"),
    ("frozenset", "엄얼린집합"),
    ("getattr", "엄속성가져와"),
    ("globals", "엄전역들"),
    ("hasattr", "엄속성있나"),
    ("hash", "엄해시"),
    ("hex", "엄십육진"),
    ("id", "엄아이디"),
    ("int", "엄정수"),
    ("isinstance", "엄인스턴스냐"),
    ("issubclass", "엄하위틀이냐"),
    ("iter", "엄반복자"),
    ("len", "엄길이"),
    ("list", "엄목록"),
    ("locals", "엄지역들"),
    ("map", "엄맵"),
    ("max", "엄최대"),
    ("memoryview", "엄메모리뷰"),
    ("min", "엄최소"),
    ("next", "엄다음"),
    ("object", "엄객체"),
    ("oct", "엄팔진"),
    ("open", "엄열어"),
    ("ord", "엄코드"),
    ("pow", "엄거듭제곱"),
    ("property", "엄속성"),
    ("quit", "엄그만"),
    ("range", "엄범위"),
    ("repr", "엄표현"),
    ("reversed", "엄뒤집어"),
    ("round", "엄반올림"),
    ("set", "엄집합"),
    ("setattr", "엄속성설정"),
    ("slice", "엄자르기"),
    ("sorted", "엄정렬된"),
    ("staticmethod", "엄정적메소드"),
    ("str", "엄문자열"),
    ("sum", "엄합"),
    ("super", "엄부모"),
    ("tuple", "엄튜플"),
    ("type", "엄타입"),
    ("vars", "엄변수들"),
    ("zip", "엄묶어"),
    ("__import__", "__엄가져와__"),
    ("NotImplemented", "엄미구현"),
    ("Ellipsis", "엄생략"),
    # 예외
    ("BaseException", "엄기본예외"),
    ("Exception", "엄예외"),
    ("ArithmeticError", "엄산술오류"),
    ("AssertionError", "엄단언오류"),
    ("AttributeError", "엄속성오류"),
    ("ConnectionError", "엄연결오류"),
    ("EOFError", "엄입력끝오류"),
    ("FileExistsError", "엄파일있음오류"),
    ("FileNotFoundError", "엄파일없음오류"),
    ("GeneratorExit", "엄생성기끝"),
    ("ImportError", "엄가져오기오류"),
    ("IndentationError", "엄들여쓰기오류"),
    ("IndexError", "엄인덱스오류"),
    ("KeyError", "엄키오류"),
    ("KeyboardInterrupt", "엄키보드중단"),
    ("LookupError", "엄찾기오류"),
    ("MemoryError", "엄메모리오류"),
    ("ModuleNotFoundError", "엄모듈없음오류"),
    ("NameError", "엄이름오류"),
    ("NotImplementedError", "엄미구현오류"),
    ("OSError", "엄운영체제오류"),
    ("OverflowError", "엄넘침오류"),
    ("PermissionError", "엄권한오류"),
    ("RecursionError", "엄재귀오류"),
    ("RuntimeError", "엄실행오류"),
    ("StopIteration", "엄반복끝"),
    ("SyntaxError", "엄문법오류"),
    ("SystemExit", "엄시스템종료"),
    ("TimeoutError", "엄시간초과오류"),
    ("TypeError", "엄타입오류"),
    ("UnicodeDecodeError", "엄유니코드해독오류"),
    ("UnicodeEncodeError", "엄유니코드인코딩오류"),
    ("UnicodeError", "엄유니코드오류"),
    ("ValueError", "엄값오류"),
    ("ZeroDivisionError", "엄영나누기오류"),
    ("Warning", "엄경고"),
    ("UserWarning", "엄사용자경고"),
    ("DeprecationWarning", "엄폐기경고"),
])

# ---------------------------------------------------------------------------
# 3. 관례 이름 / 특수(던더) 이름
# ---------------------------------------------------------------------------
SPECIAL_NAMES = OrderedDict([
    ("self", "엄슨"),
    ("cls", "엄틀자신"),
    ("args", "엄인자들"),
    ("kwargs", "엄키워드인자들"),
    ("__init__", "__엄슨시작__"),
    ("__new__", "__엄새로__"),
    ("__del__", "__엄소멸__"),
    ("__name__", "__엄이름__"),
    ("__main__", "__엄메인__"),
    ("__file__", "__엄파일__"),
    ("__doc__", "__엄설명__"),
    ("__dict__", "__엄사전__"),
    ("__class__", "__엄틀__"),
    ("__all__", "__엄모두__"),
    ("__str__", "__엄문자열__"),
    ("__repr__", "__엄표현__"),
    ("__len__", "__엄길이__"),
    ("__eq__", "__엄같나__"),
    ("__ne__", "__엄다르나__"),
    ("__lt__", "__엄작나__"),
    ("__le__", "__엄작같나__"),
    ("__gt__", "__엄크나__"),
    ("__ge__", "__엄크같나__"),
    ("__hash__", "__엄해시__"),
    ("__bool__", "__엄불__"),
    ("__add__", "__엄더하기__"),
    ("__sub__", "__엄빼기__"),
    ("__mul__", "__엄곱하기__"),
    ("__truediv__", "__엄나누기__"),
    ("__iter__", "__엄반복자__"),
    ("__next__", "__엄다음__"),
    ("__enter__", "__엄들어가__"),
    ("__exit__", "__엄나와__"),
    ("__call__", "__엄불러__"),
    ("__getitem__", "__엄항목가져와__"),
    ("__setitem__", "__엄항목설정__"),
    ("__contains__", "__엄포함__"),
    ("__getattr__", "__엄속성가져와__"),
    ("__version__", "__엄버전__"),
])

# ---------------------------------------------------------------------------
# 4. 자주 쓰는 메소드 (문자열/목록/사전/집합/파일)
# ---------------------------------------------------------------------------
METHODS = OrderedDict([
    # 문자열
    ("upper", "엄대문자"),
    ("lower", "엄소문자"),
    ("strip", "엄다듬어"),
    ("lstrip", "엄왼쪽다듬어"),
    ("rstrip", "엄오른쪽다듬어"),
    ("split", "엄쪼개"),
    ("rsplit", "엄오른쪽쪼개"),
    ("splitlines", "엄줄로쪼개"),
    ("join", "엄이어"),
    ("replace", "엄바꿔"),
    ("startswith", "엄로시작하나"),
    ("endswith", "엄로끝나나"),
    ("find", "엄찾아"),
    ("rfind", "엄뒤에서찾아"),
    ("count", "엄세어"),
    ("index", "엄위치"),
    ("isdigit", "엄숫자냐"),
    ("isalpha", "엄글자냐"),
    ("isspace", "엄공백이냐"),
    ("isupper", "엄대문자냐"),
    ("islower", "엄소문자냐"),
    ("encode", "엄인코딩"),
    ("decode", "엄디코딩"),
    ("title", "엄제목"),
    ("capitalize", "엄첫대문자"),
    ("center", "엄가운데"),
    ("ljust", "엄왼쪽맞춤"),
    ("rjust", "엄오른쪽맞춤"),
    ("zfill", "엄영채워"),
    # 목록
    ("append", "엄붙여"),
    ("extend", "엄늘려"),
    ("insert", "엄끼워"),
    ("remove", "엄빼"),
    ("pop", "엄꺼내"),
    ("clear", "엄비워"),
    ("sort", "엄정렬"),
    ("reverse", "엄뒤집기"),
    ("copy", "엄복사"),
    # 사전
    ("keys", "엄키들"),
    ("values", "엄값들"),
    ("items", "엄항목들"),
    ("get", "엄얻어"),
    ("update", "엄갱신"),
    ("setdefault", "엄기본설정"),
    ("fromkeys", "엄키로부터"),
    # 집합
    ("add", "엄추가"),
    ("discard", "엄버려"),
    ("union", "엄합집합"),
    ("intersection", "엄교집합"),
    ("difference", "엄차집합"),
    ("issubset", "엄부분집합이냐"),
    # 파일
    ("read", "엄읽어"),
    ("readline", "엄한줄읽어"),
    ("readlines", "엄줄들읽어"),
    ("write", "엄써"),
    ("writelines", "엄줄들써"),
    ("close", "엄닫아"),
    ("flush", "엄비워내"),
    ("seek", "엄위치로"),
    # 공통 인자
    ("key", "엄열쇠"),
    ("default", "엄기본값"),
    ("encoding", "엄인코딩방식"),
    ("errors", "엄오류처리"),
    ("sep", "엄구분자"),
    ("end", "엄끝문자"),
    ("file", "엄출력파일"),
    ("mode", "엄모드"),
    ("name", "엄이름"),
    ("start", "엄시작"),
    ("stop", "엄정지"),
    ("step", "엄간격"),
    ("data", "엄자료"),
])

# ---------------------------------------------------------------------------
# 5. 라이브러리 (모듈 이름 = "라이브러리 + 엄슨")
# ---------------------------------------------------------------------------
LIBRARY_GROUPS = OrderedDict()

LIBRARY_GROUPS["표준 라이브러리 모듈"] = OrderedDict([
    ("math", "수학엄슨"),
    ("random", "랜덤엄슨"),
    ("os", "운영체제엄슨"),
    ("sys", "시스템엄슨"),
    ("time", "시간엄슨"),
    ("datetime", "날짜시간엄슨"),
    ("json", "제이슨엄슨"),
    ("re", "정규식엄슨"),
    ("turtle", "거북엄슨"),
    ("subprocess", "하위프로세스엄슨"),
    ("threading", "스레딩엄슨"),
    ("queue", "큐엄슨"),
    ("pathlib", "경로립엄슨"),
    ("collections", "컬렉션엄슨"),
    ("itertools", "반복도구엄슨"),
    ("functools", "함수도구엄슨"),
    ("csv", "씨에스브이엄슨"),
    ("statistics", "통계엄슨"),
    ("shutil", "셸유틸엄슨"),
    ("tempfile", "임시파일엄슨"),
    ("dataclasses", "데이터클래스들엄슨"),
    ("typing", "타이핑엄슨"),
    ("string", "문자열모듈엄슨"),
    ("platform", "플랫폼엄슨"),
    ("pyumsn", "파이엄슨"),
    ("codecs", "코덱엄슨"),
])

LIBRARY_GROUPS["표준 라이브러리 함수·객체"] = OrderedDict([
    # math
    ("sqrt", "제곱근엄슨"),
    ("pi", "파이값엄슨"),
    ("floor", "내림엄슨"),
    ("ceil", "올림엄슨"),
    ("sin", "사인엄슨"),
    ("cos", "코사인엄슨"),
    ("tan", "탄젠트엄슨"),
    ("log", "로그엄슨"),
    ("exp", "지수엄슨"),
    ("factorial", "팩토리얼엄슨"),
    ("gcd", "최대공약수엄슨"),
    ("inf", "무한엄슨"),
    # random
    ("randint", "랜덤정수엄슨"),
    ("choice", "골라엄슨"),
    ("shuffle", "섞어엄슨"),
    ("uniform", "균등값엄슨"),
    ("seed", "씨앗엄슨"),
    ("sample", "표본엄슨"),
    # os / sys / pathlib
    ("path", "경로엄슨"),
    ("Path", "경로객체엄슨"),
    ("listdir", "목록보기엄슨"),
    ("getcwd", "현재폴더엄슨"),
    ("mkdir", "폴더만들어엄슨"),
    ("makedirs", "폴더들만들어엄슨"),
    ("exists", "존재하나엄슨"),
    ("isfile", "파일이냐엄슨"),
    ("isdir", "폴더냐엄슨"),
    ("basename", "기본이름엄슨"),
    ("dirname", "폴더이름엄슨"),
    ("abspath", "절대경로엄슨"),
    ("expanduser", "사용자경로엄슨"),
    ("splitext", "확장자분리엄슨"),
    ("gettempdir", "임시폴더엄슨"),
    ("getincrementaldecoder", "점진디코더엄슨"),
    ("cwd", "작업폴더엄슨"),
    ("env", "환경엄슨"),
    ("environ", "환경변수엄슨"),
    ("argv", "인자목록엄슨"),
    ("stdout", "표준출력엄슨"),
    ("stderr", "표준오류엄슨"),
    ("stdin", "표준입력엄슨"),
    ("executable", "실행파일엄슨"),
    ("version", "버전엄슨"),
    ("home", "집폴더엄슨"),
    ("suffix", "확장자엄슨"),
    ("parent", "부모엄슨"),
    ("read_text", "글읽어엄슨"),
    ("write_text", "글써엄슨"),
    # time / datetime
    ("sleep", "잠자엄슨"),
    ("strftime", "시간서식엄슨"),
    ("now", "지금엄슨"),
    ("today", "오늘엄슨"),
    ("date", "날짜엄슨"),
    ("timedelta", "시간차엄슨"),
    # json
    ("loads", "문자열로드엄슨"),
    ("dumps", "문자열덤프엄슨"),
    ("load", "불러와엄슨"),
    ("dump", "덤프엄슨"),
    ("indent", "들여쓰기엄슨"),
    ("ensure_ascii", "아스키보장엄슨"),
    # re
    ("search", "검색엄슨"),
    ("findall", "모두찾아엄슨"),
    ("finditer", "반복찾아엄슨"),
    ("sub", "치환엄슨"),
    ("group", "그룹엄슨"),
    # subprocess / threading / queue
    ("Popen", "프로세스열어엄슨"),
    ("run", "실행엄슨"),
    ("PIPE", "파이프엄슨"),
    ("kill", "죽여엄슨"),
    ("terminate", "종료엄슨"),
    ("wait", "기다려엄슨"),
    ("poll", "확인엄슨"),
    ("returncode", "반환코드엄슨"),
    ("Thread", "스레드엄슨"),
    ("target", "대상엄슨"),
    ("daemon", "데몬엄슨"),
    ("Queue", "대기열엄슨"),
    ("Empty", "비었음엄슨"),
    ("put", "넣어엄슨"),
    ("get_nowait", "바로얻어엄슨"),
    # collections / dataclasses
    ("Counter", "세는사전엄슨"),
    ("defaultdict", "기본값사전엄슨"),
    ("deque", "덱엄슨"),
    ("namedtuple", "이름튜플엄슨"),
    ("dataclass", "데이터클래스엄슨"),
    # turtle
    ("Turtle", "거북이엄슨"),
    ("Screen", "화면엄슨"),
    ("forward", "앞으로엄슨"),
    ("backward", "뒤로엄슨"),
    ("left", "왼쪽돌아엄슨"),
    ("right", "오른쪽돌아엄슨"),
    ("penup", "펜들어엄슨"),
    ("pendown", "펜내려엄슨"),
    ("goto", "가엄슨"),
    ("circle", "원엄슨"),
    ("speed", "속도엄슨"),
    ("done", "끝났다엄슨"),
    ("pensize", "펜굵기엄슨"),
    ("pencolor", "펜색엄슨"),
    ("fillcolor", "채울색엄슨"),
    ("begin_fill", "채우기시작엄슨"),
    ("end_fill", "채우기끝엄슨"),
    ("hideturtle", "거북숨겨엄슨"),
])

LIBRARY_GROUPS["Tkinter (티킨터엄슨)"] = OrderedDict([
    ("tkinter", "티킨터엄슨"),
    ("tk", "티엄"),
    ("ttk", "티티케이엄슨"),
    ("messagebox", "메시지박스엄슨"),
    ("filedialog", "파일대화상자엄슨"),
    ("simpledialog", "간단대화상자엄슨"),
    ("scrolledtext", "스크롤글상자엄슨"),
    ("font", "글꼴엄슨"),
    ("Tk", "창엄슨"),
    ("Toplevel", "새창엄슨"),
    ("Frame", "틀상자엄슨"),
    ("Label", "라벨엄슨"),
    ("Button", "버튼엄슨"),
    ("Entry", "입력칸엄슨"),
    ("Text", "글상자엄슨"),
    ("Canvas", "캔버스엄슨"),
    ("Scrollbar", "스크롤바엄슨"),
    ("Listbox", "목록상자엄슨"),
    ("Checkbutton", "체크버튼엄슨"),
    ("Radiobutton", "라디오버튼엄슨"),
    ("Scale", "눈금자엄슨"),
    ("Spinbox", "스핀박스엄슨"),
    ("Menu", "메뉴엄슨"),
    ("PanedWindow", "분할창엄슨"),
    ("LabelFrame", "라벨틀엄슨"),
    ("StringVar", "문자열변수엄슨"),
    ("IntVar", "정수변수엄슨"),
    ("DoubleVar", "실수변수엄슨"),
    ("BooleanVar", "불변수엄슨"),
    ("PhotoImage", "사진엄슨"),
    ("Notebook", "노트북엄슨"),
    ("Treeview", "트리뷰엄슨"),
    ("Combobox", "콤보박스엄슨"),
    ("Progressbar", "진행바엄슨"),
    ("Separator", "구분선엄슨"),
    ("Style", "스타일엄슨"),
    ("Font", "글꼴객체엄슨"),
    ("families", "글꼴목록엄슨"),
    ("mainloop", "엄슨루프"),
    ("pack", "배치엄슨"),
    ("grid", "격자엄슨"),
    ("place", "위치엄슨"),
    ("geometry", "크기엄슨"),
    ("config", "설정엄슨"),
    ("configure", "구성엄슨"),
    ("bind", "연결엄슨"),
    ("bind_all", "모두연결엄슨"),
    ("unbind", "연결끊어엄슨"),
    ("after", "나중에엄슨"),
    ("after_cancel", "나중취소엄슨"),
    ("destroy", "파괴엄슨"),
    ("delete", "삭제엄슨"),
    ("focus_set", "초점엄슨"),
    ("protocol", "프로토콜엄슨"),
    ("resizable", "크기조절엄슨"),
    ("minsize", "최소크기엄슨"),
    ("tag_configure", "태그설정엄슨"),
    ("tag_add", "태그추가엄슨"),
    ("tag_remove", "태그제거엄슨"),
    ("tag_ranges", "태그범위엄슨"),
    ("tag_bind", "태그연결엄슨"),
    ("tag_raise", "태그올려엄슨"),
    ("mark_set", "표시설정엄슨"),
    ("see", "보이게엄슨"),
    ("yview", "세로보기엄슨"),
    ("xview", "가로보기엄슨"),
    ("yscrollcommand", "세로스크롤명령엄슨"),
    ("xscrollcommand", "가로스크롤명령엄슨"),
    ("edit_modified", "수정됨엄슨"),
    ("edit_undo", "실행취소엄슨"),
    ("edit_redo", "다시실행엄슨"),
    ("event_generate", "이벤트발생엄슨"),
    ("selection", "선택엄슨"),
    ("heading", "머리글엄슨"),
    ("column", "열엄슨"),
    ("row", "행엄슨"),
    ("create_line", "선그려엄슨"),
    ("create_rectangle", "사각형그려엄슨"),
    ("create_oval", "타원그려엄슨"),
    ("create_text", "글그려엄슨"),
    ("create_polygon", "다각형그려엄슨"),
    ("coords", "좌표엄슨"),
    ("move", "이동엄슨"),
    ("itemconfig", "항목설정엄슨"),
    ("showinfo", "정보보여엄슨"),
    ("showerror", "오류보여엄슨"),
    ("showwarning", "경고보여엄슨"),
    ("askyesno", "예아니오물어엄슨"),
    ("askyesnocancel", "예아니오취소물어엄슨"),
    ("askopenfilename", "열파일물어엄슨"),
    ("asksaveasfilename", "저장파일물어엄슨"),
    ("askstring", "문자열물어엄슨"),
    ("askinteger", "정수물어엄슨"),
    ("text", "글엄슨"),
    ("command", "명령엄슨"),
    ("width", "너비엄슨"),
    ("height", "높이엄슨"),
    ("bg", "배경엄슨"),
    ("fg", "전경엄슨"),
    ("background", "배경색엄슨"),
    ("foreground", "전경색엄슨"),
    ("padx", "가로여백엄슨"),
    ("pady", "세로여백엄슨"),
    ("side", "쪽엄슨"),
    ("fill", "채우기엄슨"),
    ("expand", "확장엄슨"),
    ("sticky", "붙이기엄슨"),
    ("textvariable", "글변수엄슨"),
    ("relief", "테두리모양엄슨"),
    ("state", "상태엄슨"),
    ("anchor", "기준엄슨"),
    ("justify", "정렬엄슨"),
    ("orient", "방향엄슨"),
    ("variable", "변수엄슨"),
    ("value", "값엄슨"),
    ("label", "이름표엄슨"),
    ("menu", "메뉴판엄슨"),
    ("underline", "밑줄엄슨"),
    ("wrap", "줄바꿈엄슨"),
    ("undo", "되돌리기엄슨"),
    ("insertbackground", "커서색엄슨"),
    ("selectbackground", "선택배경엄슨"),
    ("highlightthickness", "강조두께엄슨"),
    ("highlightbackground", "강조배경엄슨"),
    ("highlightcolor", "강조색엄슨"),
    ("borderwidth", "테두리두께엄슨"),
    ("cursor", "마우스모양엄슨"),
    ("accelerator", "단축키엄슨"),
    ("tearoff", "떼어내기엄슨"),
    ("add_command", "명령추가엄슨"),
    ("add_cascade", "하위메뉴추가엄슨"),
    ("add_separator", "구분선추가엄슨"),
    ("filetypes", "파일종류엄슨"),
    ("initialfile", "처음파일엄슨"),
    ("defaultextension", "기본확장자엄슨"),
    ("widget", "위젯엄슨"),
    ("keysym", "키이름엄슨"),
    ("delta", "변화량엄슨"),
    ("END", "끝엄슨"),
    ("INSERT", "삽입엄슨"),
    ("LEFT", "왼쪽엄슨"),
    ("RIGHT", "오른쪽엄슨"),
    ("TOP", "위엄슨"),
    ("BOTTOM", "아래엄슨"),
    ("BOTH", "양쪽엄슨"),
    ("X", "가로엄슨"),
    ("Y", "세로엄슨"),
    ("N", "북엄슨"),
    ("S", "남엄슨"),
    ("E", "동엄슨"),
    ("W", "서엄슨"),
    ("NORMAL", "보통엄슨"),
    ("DISABLED", "비활성엄슨"),
    ("WORD", "단어엄슨"),
    ("NONE", "없음엄슨"),
    ("HORIZONTAL", "수평엄슨"),
    ("VERTICAL", "수직엄슨"),
    ("SEL", "선택영역엄슨"),
    ("SEL_FIRST", "선택처음엄슨"),
    ("SEL_LAST", "선택마지막엄슨"),
    ("TclError", "티클오류엄슨"),
    ("TkVersion", "티케이버전엄슨"),
    ("edit_separator", "편집구분엄슨"),
    ("edit_reset", "편집초기화엄슨"),
    ("select", "고르기엄슨"),
    ("weight", "굵기엄슨"),
    ("family", "글꼴이름엄슨"),
    ("slant", "기울기엄슨"),
    ("measure", "재기엄슨"),
    ("activebackground", "활성배경엄슨"),
    ("activeforeground", "활성전경엄슨"),
    ("disabledforeground", "비활성전경엄슨"),
    ("selectforeground", "선택전경엄슨"),
    ("cget", "설정값엄슨"),
    ("sashwidth", "경계너비엄슨"),
    ("stretch", "늘이기엄슨"),
    ("forget", "잊어엄슨"),
    ("panes", "칸들엄슨"),
    ("tabs", "탭들엄슨"),
    ("tab", "탭엄슨"),
    ("nametowidget", "이름으로위젯엄슨"),
    ("columnspan", "열합치기엄슨"),
    ("rowspan", "행합치기엄슨"),
    ("grid_rowconfigure", "격자행설정엄슨"),
    ("grid_columnconfigure", "격자열설정엄슨"),
    ("stopindex", "멈출위치엄슨"),
    ("selection_set", "선택설정엄슨"),
    ("selection_clear", "선택해제엄슨"),
    ("curselection", "현재선택엄슨"),
    ("selectmode", "선택방식엄슨"),
    ("get_children", "자식들엄슨"),
    ("item", "항목엄슨"),
    ("dlineinfo", "줄정보엄슨"),
    ("bbox", "경계상자엄슨"),
    ("tag_names", "태그이름들엄슨"),
    ("tag_prevrange", "앞태그범위엄슨"),
    ("tag_lower", "태그내려엄슨"),
    ("tk_popup", "팝업엄슨"),
    ("x_root", "화면가로엄슨"),
    ("y_root", "화면세로엄슨"),
    ("winfo_rootx", "화면가로위치엄슨"),
    ("winfo_rooty", "화면세로위치엄슨"),
    ("winfo_exists", "존재확인엄슨"),
    ("winfo_width", "실제너비엄슨"),
    ("winfo_height", "실제높이엄슨"),
    ("wm_overrideredirect", "테두리없애엄슨"),
    ("transient", "딸린창엄슨"),
    ("lift", "올려엄슨"),
    ("theme_use", "테마사용엄슨"),
    ("trace_add", "추적추가엄슨"),
    ("clipboard_clear", "클립보드비워엄슨"),
    ("clipboard_append", "클립보드추가엄슨"),
    ("fieldbackground", "칸배경엄슨"),
    ("rowheight", "행높이엄슨"),
    ("padding", "안쪽여백엄슨"),
    ("activestyle", "활성모양엄슨"),
    ("exportselection", "선택내보내기엄슨"),
    ("maxundo", "최대되돌리기엄슨"),
    ("autoseparators", "자동구분엄슨"),
    ("minvalue", "최솟값엄슨"),
    ("maxvalue", "최댓값엄슨"),
])

LIBRARY_GROUPS["NumPy (넘파이엄슨)"] = OrderedDict([
    ("numpy", "넘파이엄슨"),
    ("np", "넘엄"),
    ("array", "배열엄슨"),
    ("ndarray", "엔디배열엄슨"),
    ("zeros", "영배열엄슨"),
    ("ones", "일배열엄슨"),
    ("full", "채운배열엄슨"),
    ("eye", "단위행렬엄슨"),
    ("arange", "범위배열엄슨"),
    ("linspace", "균등배열엄슨"),
    ("reshape", "모양바꿔엄슨"),
    ("shape", "모양엄슨"),
    ("dtype", "자료형엄슨"),
    ("astype", "형변환엄슨"),
    ("tolist", "목록으로엄슨"),
    ("size", "크기값엄슨"),
    ("mean", "평균엄슨"),
    ("median", "중앙값엄슨"),
    ("std", "표준편차엄슨"),
    ("var", "분산엄슨"),
    ("dot", "내적엄슨"),
    ("matmul", "행렬곱엄슨"),
    ("transpose", "전치엄슨"),
    ("concatenate", "이어붙여엄슨"),
    ("argmax", "최대위치엄슨"),
    ("argmin", "최소위치엄슨"),
    ("where", "어디엄슨"),
    ("unique", "고유값엄슨"),
    ("linalg", "선형대수엄슨"),
    ("rand", "랜덤값엄슨"),
    ("randn", "정규랜덤엄슨"),
])

LIBRARY_GROUPS["Pandas (판다스엄슨)"] = OrderedDict([
    ("pandas", "판다스엄슨"),
    ("pd", "판엄"),
    ("DataFrame", "데이터프레임엄슨"),
    ("Series", "시리즈엄슨"),
    ("read_csv", "씨에스브이읽어엄슨"),
    ("to_csv", "씨에스브이로엄슨"),
    ("read_excel", "엑셀읽어엄슨"),
    ("to_excel", "엑셀로엄슨"),
    ("head", "머리엄슨"),
    ("tail", "꼬리엄슨"),
    ("describe", "요약엄슨"),
    ("info", "정보엄슨"),
    ("groupby", "묶어보기엄슨"),
    ("loc", "위치로엄슨"),
    ("iloc", "번호로엄슨"),
    ("columns", "열들엄슨"),
    ("sort_values", "값정렬엄슨"),
    ("dropna", "결측빼엄슨"),
    ("fillna", "결측채워엄슨"),
    ("isnull", "결측이냐엄슨"),
    ("merge", "병합엄슨"),
    ("concat", "합쳐엄슨"),
    ("apply", "적용엄슨"),
    ("value_counts", "값세어엄슨"),
    ("drop", "떨궈엄슨"),
    ("rename", "이름바꿔엄슨"),
    ("iterrows", "행반복엄슨"),
    ("agg", "집계엄슨"),
    ("axis", "축엄슨"),
    ("index_col", "인덱스열엄슨"),
])

LIBRARY_GROUPS["Matplotlib (맷플롯립엄슨)"] = OrderedDict([
    ("matplotlib", "맷플롯립엄슨"),
    ("pyplot", "파이플롯엄슨"),
    ("plt", "플엄"),
    ("use", "사용엄슨"),
    ("get_backend", "백엔드확인엄슨"),
    ("rcParams", "설정값들엄슨"),
    ("font_manager", "글꼴관리자엄슨"),
    ("fontManager", "글꼴관리객체엄슨"),
    ("ttflist", "글꼴파일목록엄슨"),
    ("plot", "그려엄슨"),
    ("show", "보여엄슨"),
    ("xlabel", "가로이름엄슨"),
    ("ylabel", "세로이름엄슨"),
    ("legend", "범례엄슨"),
    ("scatter", "산점도엄슨"),
    ("bar", "막대엄슨"),
    ("hist", "히스토그램엄슨"),
    ("pie", "원그래프엄슨"),
    ("figure", "그림엄슨"),
    ("subplot", "작은그림엄슨"),
    ("subplots", "작은그림들엄슨"),
    ("savefig", "그림저장엄슨"),
    ("xlim", "가로범위엄슨"),
    ("ylim", "세로범위엄슨"),
    ("color", "색엄슨"),
    ("linewidth", "선굵기엄슨"),
    ("marker", "표시엄슨"),
    ("alpha", "투명도엄슨"),
    ("figsize", "그림크기엄슨"),
    ("tight_layout", "빽빽배치엄슨"),
    ("set_title", "제목설정엄슨"),
    ("set_xlabel", "가로이름설정엄슨"),
    ("set_ylabel", "세로이름설정엄슨"),
])

LIBRARY_GROUPS["PyUMSN API (파이엄슨)"] = OrderedDict([
    ("umsn_to_py", "엄슨을파이썬으로"),
    ("py_to_umsn", "파이썬을엄슨으로"),
    ("check_umsn", "엄슨검사"),
    ("tokenize_umsn", "엄슨토큰나눠"),
    ("highlight_spans", "색칠구간엄슨"),
    ("transliterate", "음역엄슨"),
    ("untransliterate", "음역풀어엄슨"),
    ("read_source", "소스읽어엄슨"),
    ("write_source", "소스써엄슨"),
    ("build_command", "실행명령만들어엄슨"),
    ("child_env", "자식환경엄슨"),
    ("all_words", "모든단어엄슨"),
    ("category_of", "분류알아엄슨"),
    ("UmsnError", "엄슨오류"),
    ("UmsnSyntaxError", "엄슨문법오류"),
    ("UmsnEncodingError", "엄슨인코딩오류"),
    ("lineno", "줄번호엄슨"),
    ("col", "칸번호엄슨"),
    ("problems", "문제들엄슨"),
    ("runner", "실행기엄슨"),
    ("vocab", "어휘엄슨"),
    ("make_temp_py", "임시파이썬만들어엄슨"),
    ("remove_quietly", "조용히지워엄슨"),
    ("run_file", "파일실행엄슨"),
    ("install_import_hook", "가져오기고리설치엄슨"),
    ("unbuffered", "버퍼없이엄슨"),
    ("report", "보고엄슨"),
    ("msg", "메시지엄슨"),
    ("filename", "파일이름엄슨"),
    ("source", "소스엄슨"),
    ("kind", "종류엄슨"),
    ("UMSN2PY", "엄슨파이썬표"),
    ("PY2UMSN", "파이썬엄슨표"),
    ("UMSN2SYMBOL", "엄슨기호표"),
    ("SYMBOL2UMSN", "기호엄슨표"),
])

LIBRARIES = OrderedDict()
for _group in LIBRARY_GROUPS.values():
    LIBRARIES.update(_group)

# ---------------------------------------------------------------------------
# 6. 기호 (문장부호/연산자) → ``..`` + 한글 기호어
# ---------------------------------------------------------------------------
SYMBOL_PREFIX = ".."

SYMBOLS = OrderedDict([
    ("()", "하다"),
    ("(", "하"),
    (")", "다"),
    ("[]", "엄슨"),
    ("[", "엄"),
    ("]", "슨"),
    ("{}", "어엄슨"),
    ("{", "어엄"),
    ("}", "어슨"),
    (":", "한"),
    (",", "고"),
    (";", "끝"),
    ("=", "은"),
    ("==", "같슨"),
    ("!=", "다르슨"),
    ("<", "작슨"),
    (">", "크슨"),
    ("<=", "작같슨"),
    (">=", "크같슨"),
    ("+", "더해"),
    ("-", "빼"),
    ("*", "곱해"),
    ("/", "나눠"),
    ("//", "몫"),
    ("%", "나머지"),
    ("**", "제곱"),
    ("@", "행렬곱"),
    ("+=", "더해은"),
    ("-=", "빼은"),
    ("*=", "곱해은"),
    ("/=", "나눠은"),
    ("//=", "몫은"),
    ("%=", "나머지은"),
    ("**=", "제곱은"),
    ("@=", "행렬곱은"),
    ("&", "비트곱"),
    ("|", "비트합"),
    ("^", "비트차"),
    ("~", "비트반전"),
    ("<<", "왼밀어"),
    (">>", "오른밀어"),
    ("&=", "비트곱은"),
    ("|=", "비트합은"),
    ("^=", "비트차은"),
    ("<<=", "왼밀어은"),
    (">>=", "오른밀어은"),
    ("->", "화살"),
    (":=", "바다코끼리"),
])

# ---------------------------------------------------------------------------
# 7. 문자열 접두사 (f/r/b/u/t → 형/날/바/유/템, 대문자는 앞에 "대")
# ---------------------------------------------------------------------------
STRING_PREFIX_CHARS = OrderedDict([
    ("f", "형"),
    ("r", "날"),
    ("b", "바"),
    ("u", "유"),
    ("t", "템"),
])
UPPER_MARK = "대"

# ---------------------------------------------------------------------------
# 8. 음역 (사전에 없는 영어 이름 ↔ 한글)  예: polyfit → 외_피오르야프이트
# ---------------------------------------------------------------------------
TRANSLIT_MARK = "외_"
TRANSLIT_LETTERS = OrderedDict([
    ("a", "아"), ("b", "브"), ("c", "크"), ("d", "드"), ("e", "에"),
    ("f", "프"), ("g", "그"), ("h", "흐"), ("i", "이"), ("j", "즈"),
    ("k", "키"), ("l", "르"), ("m", "므"), ("n", "느"), ("o", "오"),
    ("p", "피"), ("q", "쿠"), ("r", "러"), ("s", "스"), ("t", "트"),
    ("u", "우"), ("v", "뷔"), ("w", "워"), ("x", "엑"), ("y", "야"),
    ("z", "지"),
])

# ---------------------------------------------------------------------------
# 분류 / 역사전
# ---------------------------------------------------------------------------
CATEGORIES = OrderedDict([
    ("keyword", ("예약어", KEYWORDS)),
    ("builtin", ("내장 함수·예외", BUILTINS)),
    ("special", ("관례·특수 이름", SPECIAL_NAMES)),
    ("method", ("메소드·인자", METHODS)),
    ("library", ("라이브러리", LIBRARIES)),
])

PY2UMSN = OrderedDict()
WORD_CATEGORY = {}
for _cat, (_title, _table) in CATEGORIES.items():
    for _py, _um in _table.items():
        if _py in PY2UMSN:
            raise RuntimeError("엄슨 어휘 중복(파이썬 이름): %r" % _py)
        PY2UMSN[_py] = _um
        WORD_CATEGORY[_um] = _cat

UMSN2PY = OrderedDict()
for _py, _um in PY2UMSN.items():
    if _um in UMSN2PY:
        raise RuntimeError("엄슨 어휘 중복(엄슨 단어): %r (%r, %r)" % (_um, UMSN2PY[_um], _py))
    UMSN2PY[_um] = _py

SYMBOL2UMSN = OrderedDict((py, SYMBOL_PREFIX + um) for py, um in SYMBOLS.items())
UMSN2SYMBOL = OrderedDict((um, py) for py, um in SYMBOL2UMSN.items())
if len(UMSN2SYMBOL) != len(SYMBOL2UMSN):
    raise RuntimeError("엄슨 기호어 중복")
# 최장 일치를 위해 긴 기호어부터
SYMBOL_WORDS_BY_LENGTH = sorted(UMSN2SYMBOL, key=len, reverse=True)

TRANSLIT_REVERSE = {v: k for k, v in TRANSLIT_LETTERS.items()}
PREFIX_REVERSE = {v: k for k, v in STRING_PREFIX_CHARS.items()}


def all_words():
    """(분류, 엄슨 단어, 파이썬 이름) 목록. IDE 단어장·자동완성용."""
    result = []
    for cat, (title, table) in CATEGORIES.items():
        for py, um in table.items():
            result.append((title, um, py))
    for py, um in SYMBOL2UMSN.items():
        result.append(("기호", um, py))
    return result


def category_of(word):
    """엄슨 단어의 분류 이름(keyword/builtin/special/method/library) 또는 None."""
    return WORD_CATEGORY.get(word)
